name = "Theseus S3"
author = "ExplosiveJoe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bd1db3c50ccada08e60f9129d573e5377e349ba928b89e29a6b444e778924ec"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
