name = "Theseus S3"
author = "ExplosiveJoe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3078c7608d71035623a68e70c16300ffde9b7c285c7897d7e2ec79409ab7792"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
