name = "Theseus S3"
author = "ExplosiveJoe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fc0a3fe50e1a9b8f483c014913c551f8b20e1e4e722f4d36a95d5a31bd99e5a"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
